title: Интерей Контракт
# --- begin seo
# see also
#  - https://github.com/jekyll/jekyll-seo-tag
#  - https://gregberge.com/blog/gatsby-seo,
#  - https://search.google.com/search-console/about
#  - https://toolbox.seositecheckup.com/users
description: >-
  Интерей Контракт e счетоводна фирма, чиято цел вашият растеж. Предлага
  счетоводни, данъчни и финансови услуги и консултации, както и помощ при
  управление на европейски проекти; Защита при ревизии и данъчни проверки.
  Ваш партньор в обработката на ТРЗ, ЗКПО, ЗДДФЛ, ЗДДС както и посредник при
  работата с НОИ и НАП.
url: "https://www.accounting24.bg"
canonical_url: "https://www.accounting24.bg/"
lang: bg_BG
#logo: /assets/logo.png
#social:
#  name: Interey Kontract
#  links:
#    - https://www.facebook.com/interey.kontract
#    - https://www.linkedin.com/in/interey.kontract
# --- end seo
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
landing_template: home
palette: green
palettes:
  blue:
    sass:
      accent1: '#4598c8'
      accent2: '#93d7ff'
      accent3: '#b8d5ff'
      accent4: '#a2f7c2'
      accent5: '#6289c3'
      accent6: '#53b678'
  green:
    sass:
      accent1: '#21b2a6'
      accent2: '#00ffcc'
      accent3: '#00f0ff'
      accent4: '#76ddff'
      accent5: '#505393'
      accent6: '#ed4933'
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
